fconc: fconc.o doWrite.o write_file.o
	gcc -o fconc fconc.o doWrite.o write_file.o

fconc.o: fconc.c
	gcc -Wall -c fconc.c

doWrite.o: doWrite.c
	gcc -Wall -c doWrite.c

write_file.o: write_file.c
	gcc -Wall -c write_file.c


