given-tree: given-tree.o proc-common.o tree.o
	gcc -Wall -o given-tree given-tree.o proc-common.o tree.o
given-tree.o: given-tree.c
	gcc -Wall -c given-tree.c
proc-common.o: proc-common.c
	gcc -Wall -c proc-common.c
tree.o: tree.c
	gcc -Wall -c tree.c
