ask2-signals: ask2-signals.o proc-common.o tree.o
	gcc -Wall -o ask2-signals ask2-signals.o proc-common.o tree.o
ask2-signals.o: ask2-signals.c
	gcc -Wall -c ask2-signals.c
proc-common.o: proc-common.c
	gcc -Wall -c proc-common.c
tree.o: tree.c
	gcc -Wall -c tree.c
