pipes: pipes.o proc-common.o tree.o
	gcc -Wall -o pipes pipes.o proc-common.o tree.o
pipes.o: pipes.c
	gcc -Wall -c pipes.c
proc-common.o: proc-common.c
	gcc -Wall -c proc-common.c
tree.o: tree.c
	gcc -Wall -c tree.c
